config/routes.rb
Rails.application.routes.draw do

  root "pages#index", as: :main

  resources :spots
  resources :users
  resources :places do
    resources :pics
  end

  patch 'im_here' => 'attendees#im_here'
  post 'subscriptions' => 'subscriptions#create'

  get '/categories' => 'categories#index'
  namespace :categories do
    get '/restaurants' => 'restaurants#index'
    get '/bars' => 'bars#index'
    get '/intellectual' => 'intellectual#index'
    get '/shopping' => 'shopping#index'
    get '/bored' => 'bored#index'
    get '/active' => 'active#index'
    get '/outdoors' => 'outdoors#index'
    get '/broke' => 'broke#index'
  end
  post '/attendees' => 'attendees#create'

  get '/signin' => 'authenticates#signin'
  post '/signin' => 'authenticates#create'

  get '/signup' => 'registers#signup'
  post '/signup' => 'registers#create'

  get '/signout' => 'authenticates#destroy'

end

app/models/spot.rb
class Spot <ActiveRecord::Base
  # after_initialize do
  #   if self.new_record?
  #     self.start_time = Time.now
  #     self.end_time = Time.now + 2.hours
  #     self.date = Time.now.to_date
  #   end
  # end

  validates :start_time, presence: true
  validates :description, presence: true
  validates :place, presence: true

  belongs_to :place

  has_many :comments
  has_many :attendees
  has_many :users, through: :attendees
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  def index
    @spots = Spot.all.order("date")
  end

  def new
    @spot = Spot.new
  end

  def edit
  end

  def show
    @attendee = @spot.attendees.find_by_user_id(current_user.id)
    # raise @spot.attendees.map{|a| [a.id, a.user.full_name] }.inspect
  end

  def create
    @spot = Spot.new(spot_params)
    Attendee.create!(
      user: current_user,
      spot: @spot,
      role: "Attendant"
    )
    if params[:invited_friends]
      params[:invited_friends].each do |friend_id|
        Attendee.create!(
          user: User.find(friend_id),
          spot: @spot,
          role: 'Attendee'
        )
      end
    end

    if @spot.save
      redirect_to spot_path(@spot), notice: "Spot successfully created"
    else
      render :new
    end
  end

  def update
    if @spot.update(spot_params)
      redirect_to spots_path
    else
      render :edit
    end
  end

  def destroy
    @spot.destroy
    redirect_to spots_path
  end

  def set_spot
    @spot = Spot.find(params[:id])
  end

  def spot_params
    params.require(:spot).permit(:place_id, :description, :date, :start_time, :end_time)
  end
end

app/helpers/spot_helper.rb
module SpotHelper
end

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <div class = "row">

    <div class="well form-inline text-center col-md-4 col-md-offset-4">
      <center><h2> <%= title %> </h2></center>
      <%= render '/errors', model: @spot %>

      <br><div class='form-group'>
        <%= f.collection_select(:place_id, subbed_places, :id, :name, {prompt: "Select a place"}, {class: "form-control"}) %>
      </div><br><br>

      <div class='form-group'>
        <%= f.text_field :description, placeholder: "Description", class: 'form-control' %>
      </div><br><br>

      <div class='form-group'>
        <%= f.date_field :date, class: 'form-control' %>
      </div><br><br>

      <div class='form-group'>
        <% start_time = @spot.start_time || Time.now %>
        <%= f.time_field :start_time, value: start_time.strftime("%I:%M"), class: 'form-control' %>
      </div><br><br>

      <div class='form-group'>
        <% end_time = @spot.end_time || start_time + 2.hours %>
        <%= f.time_field :end_time, value: end_time.strftime("%I:%M"), class: 'form-control' %>
      </div><br><br>

      <% my_friends.each do |friend| %>
        <%= check_box_tag 'invited_friends[]', friend.id %>
        <%= friend.full_name %><br>
      <% end %><br>

      <div class='form-group'>
        <%= f.submit class: "btn btn-submit form-control", data: {confirm: "Are you sure?"} %>
      </div><br><br>
      <%= link_to 'To Index', spots_path, {style: 'color:black'} %>
    </div>
  </div>
<% end %>

app/views/spots/_going_form.html.erb
<%= form_for @attendee do |f| %>
  <%= hidden_field_tag :spot_id, mod %>
  <%= f.submit "I'm Going!", class: 'btn btn-submit' %>
<% end %>

app/views/spots/_spot_something_form.html.erb
<%= form_for @spot_nav do |f| %>
  <div class='form-inline' style='opacity:0.7'>
    <div class='form-group'>
      <%= link_to content_tag(:span, "", class: "glyphicon glyphicon-pencil"), new_spot_path %>
    </div>

    <div class='form-group'>
      <%= f.text_field :description, autofocus: true, placeholder: "Description", class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.collection_select(:place_id, subbed_places, :id, :name, {prompt: "Place"}, {class: "form-control"}) %>
    </div>

    <div class='form-group'>
      <%= f.date_field :date, value: Date.today, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.time_field :start_time, value: Time.now.strftime("%I:%M"), class: 'form-control' %> to
    </div>

    <div class='form-group'>
      <%= f.time_field :end_time, value: (Time.now + 2.hours).strftime("%I:%M"), class: 'form-control' %>
    </div>

    <%= form_for @attendee_nav do |f| %>
      <div class='form-group'>
        <%= f.collection_select(:user_id, my_friends, :id, :first_name, {prompt: "Invite Friends"}, {class: "form-control"}) %>
      </div>
    <% end %>

    <div class='form-group' style='opacity: 1.2'>
      <%= image_submit_tag("spot-icon.png", style: 'border-radius:7px', width: "45em", height: "30em", alt: "Spot Something")%>
    </div>
  </div>
<% end %>

app/views/spots/edit.html.erb
  <%= render 'form', title: 'Edit Spot' %>

app/views/spots/index.html.erb
<%= page_header "Spots" do%>
<% end %>
  <table class = 'table'>
    <thead>
      <tr>
        <th>
          <h3>Location</h3>
        </th>

        <th>
          <h3>Date</h3>
        </th>

        <th>
          <h3>Time</h3>
        </th>

        <th>
          <h3>Description</h3>
        </th>

        <th>
          <h3>Others</h3>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @spots.each do |spot| %>
        <tr>
          <td>
            <%= link_to spot.place.name, spot_path(spot) %>
          </td>

          <td>
            <%= spot.date.strftime("%b%-d") %>
          </td>

          <td>
            <%= spot.start_time.strftime("%I:%M%p") %>
          </td>

          <td>
            <%= spot.description %>
          </td>

          <td>
            <% spot.attendees.each do |attendee| %>
              <%= link_to attendee.user.full_name, user_path(attendee.user)%>
              <% unless attendee == spot.attendees.last %>,<% end %>
            <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/spots/new.html.erb
  </div>
  <%= render 'form', title: 'New Spot' %>

app/views/spots/new_spot.html.erb
<% @new_spot = true %>
as;dfjasdoifajsdfioj

app/views/spots/show.html.erb
</div>
<div class = 'container jumbotron text-center'>

  <h1><%= link_to @spot.place.name, place_path(@spot.place) %></h1>
  <h2>at <%= @spot.start_time.strftime("%I:%M%p")  %> </h2>
  <h2>to <%= @spot.end_time.strftime("%I:%M%p")  %></h2><br>

  <h2> <%= @spot.description %> </h2><br>

  with...
  <h3>
    <% @spot.attendees.where(role: 'Attendant').order('arrived DESC').each do |attendant| %>
      <%= image_tag('crown.png', width: '20em') %> <%= link_to attendant.user.full_name, user_path(attendant.user) %>
      <% if attendant.arrived %><small>(Here)</small><% else %><small>(Not here yet)</small><% end %><br>
    <% end %>

    <% @spot.attendees.where(role: 'Attendee').order('arrived DESC').each do |attendee| %>
      <%= link_to attendee.user.full_name, user_path(attendee.user) %>
      <% if attendee.arrived %><small>(Here)</small><% else %><small>(Not here yet)</small><% end %><br>
    <% end %>
  </h3>

  <% spot_attendees = @spot.attendees.map(&:user) %>

  <% if spot_attendees.include?(current_user) %>
    <%= form_for @attendee, url: {action: "im_here", controller: 'attendees', params: {spot_id: @spot.id, attendee_id: @attendee.id}} do |f| %>
      <% if !@attendee.arrived %>
        <%= f.submit "I'm Here!", class: 'btn-submit' %>
      <% else %>
        <%= f.submit "I'm Not Here!", class: 'btn-submit' %>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class='container'>
  <%= link_to 'Edit', edit_spot_path(@spot) %>
  <%= link_to 'Delete', spot_path, method: :delete, data: {confirm: 'Are you sure?'} %>
</div>