config/routes.rb
Rails.application.routes.draw do

  root "pages#index", as: :main

  resources :spots
  resources :users
  resources :places do
    resources :pics
  end

  patch 'im_here' => 'attendees#im_here'
  post 'subscriptions' => 'subscriptions#create'

  get '/categories' => 'categories#index'
  namespace :categories do
    get '/restaurants' => 'restaurants#index'
    get '/bars' => 'bars#index'
    get '/intellectual' => 'intellectual#index'
    get '/shopping' => 'shopping#index'
    get '/bored' => 'bored#index'
    get '/active' => 'active#index'
    get '/outdoors' => 'outdoors#index'
    get '/broke' => 'broke#index'
  end
  post '/attendees' => 'attendees#create'

  get '/signin' => 'authenticates#signin'
  post '/signin' => 'authenticates#create'

  get '/signup' => 'registers#signup'
  post '/signup' => 'registers#create'

  get '/signout' => 'authenticates#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  def full_name
    "#{first_name} #{last_name}"
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  belongs_to :comment
  belongs_to :subscription

  has_many :friends
  has_many :spots, through: :attendees
  has_many :attendees
  has_many :comments
  has_many :subscriptions
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def create
    skip_before_action :ensure_logged_in
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%= form_for model do |f| %>

  <div class = "row">
    <div class="well col-md-4 col-md-offset-4 text-center">
      <dl class = 'dl-horizontal'>

      <h2> <%= title %> </h2>
      <br>

      <%= render '/errors.html.erb', model: model %>

      <%= f.text_field :first_name, placeholder: 'First name', autofocus: true, class: "form-control" %>
      <br>
      <%= f.text_field :last_name, placeholder: 'Last name', class: "form-control" %>
      <br>
      <%= f.email_field :email, placeholder: 'E-mail', class: "form-control"%>
      <br>
      <%= f.password_field :password, placeholder: 'Password', class: "form-control" %>
      <br>
      <%= f.password_field :password_confirmation, placeholder: 'Password confirmation', class: "form-control" %>
      <br>

      <% if @signup %>
        <%= f.submit 'Sign Up!',class: 'btn btn-submit' %>
      <% else %>
        <%= f.submit class: 'btn btn-submit' %>
      <% end %>

      <% if @edit_user %>
        <%= link_to 'Delete User', user_path(@user), method: :delete, class: 'btn btn-danger' %>
      <% end %>

    </div>
  </div>

<% end %>

app/views/users/_signin_form.html.erb
<%= form_for(model, url: path) do |f|%>
  <div class = "row">
    <div class="well col-md-4 col-md-offset-4 text-center">
      <dl class = 'dl-horizontal'>

        <% if @sign_in_error %>
          <div class = 'error'>
            <br><p><%= @sign_in_error %></p>
          </div>
        <% end %>
        <br>

        <h1>Sign in</h1>
        <br>
        <%= f.email_field :email, placeholder: 'E-mail', class: "form-control", autofocus: true%>
        <br>
        <%= f.password_field :password, placeholder: 'Password', class: "form-control" %>
        <br>
        <%= f.submit "Sign In", class: "btn-submit center" %>
      </dl>
    <%= link_to 'Register Here', signup_path, style: 'color:black' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% @edit_page = true %>
<%= render 'form',
    model: @user,
    path: user_path,
    title: 'Edit User' %>
<!-- <%= link_to 'To Index', users_path %> -->

app/views/users/index.html.erb
<%= page_header "Users" do%>
  <%= link_to "New User", new_user_path, :class => "btn btn-submit pull-right" %>
<% end %>

  <table class = "table">
    <thead>
      <tr>
        <th>
          <h3>Name</h3>
        </th>
        <th>
          <h3>E-Mail</h3>
        </th>
        <th>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <% if user.first_name && user.last_name %>
            <% full_name = (user.first_name + " " + user.last_name) %>
            <%= link_to full_name, user_path(user)%>
          <% end %>
        </td>
        <td>
          <%= mail_to(user.email) %>
        </td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/show.html.erb
  <h1>
    <%= @user.full_name %>
    <%= link_to 'Edit', edit_user_path(@user), :class=>'btn btn-primary pull-right' %>
  </h1>
  <%= image_tag(@user.avatar, width: "200em") %>

  <dl class = 'dl-horizontal'>

    <dt>First Name:</dt>
    <dd><%= @user.first_name %></dd>

    <dt>Last Name:</dt>
    <dd><%= @user.last_name %></dd>

    <dt>E-Mail:</dt>
    <dd><%= mail_to(@user.email) %></dd><br>

    <dt>Subscriptions:</dt>
    <dd>
      <% User.find(current_user).subscriptions.each do |subs| %>
        <%= link_to subs.place.name, place_path(subs.place) %><br>
      <% end %>
    </dd>
  </dl>

  <hr>
  <h2>Current Spots</h2>
  <% @user.spots.each do |spot| %>
    <% if (spot.start_time < Time.now) and (spot.end_time > Time.now) and (spot.date == Date.today) %>
      <div class = 'container jumbotron text-center index-jumbos'>
        <h3><%= link_to "#{spot.place.name} @ #{spot.start_time.strftime("%I:%M%p")}", spot_path(spot) %></h3>
        <h4> <%= spot.description %> </h4>
      </div>
    <% end %>
  <% end %>

  <hr>
  <a href='#'><h2 data-toggle='collapse' data-target='.upcoming'>Upcoming Spots</h2></a>
  <div class='collapse upcoming'>
  <% @user.spots.each do |spot| %>
    <% if (Date.today < spot.date) or (Date.today == spot.date and spot.start_time > Time.now)%>
      <div class = 'container jumbotron text-center index-jumbos'>
        <h3><%= link_to "#{spot.place.name} @ #{spot.start_time.strftime("%I:%M%p")}", spot_path(spot) %></h3>
        <h4> <%= spot.description %> </h4>
      </div>
    <% end %>
  <% end %>
  </div>

  <hr>
  <a href='#'><h2 data-toggle='collapse' data-target='.previous'>Previous Spots</h2></a>
  <div class='collapse previous'>
  <% @user.spots.each do |spot| %>
    <% if (Date.today > spot.date ) or (Date.today == spot.date and spot.start_time < Time.now)%>
      <div class = 'container jumbotron text-center index-jumbos'>
        <h3><%= link_to "#{spot.place.name} @ #{spot.start_time.strftime("%I:%M%p")}", spot_path(spot) %></h3>
        <h4> <%= spot.description %> </h4>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/signin.html.erb
<%= render 'users/signin_form',
  title: 'Sign into Spot',
  button: 'Sign In!',
  path: signin_path,
  model: :session %>

app/views/users/signup.html.erb
<% @signup = true %>
<%= render 'users/form',
  title: 'Sign up for Spot!',
  button: 'Sign Up!',
  model: @user %>