config/routes.rb
Rails.application.routes.draw do

  root "pages#index", as: :main

  resources :spots
  resources :users
  resources :places do
    resources :pics
  end

  patch 'im_here' => 'attendees#im_here'
  post 'subscriptions' => 'subscriptions#create'

  get '/categories' => 'categories#index'
  namespace :categories do
    get '/restaurants' => 'restaurants#index'
    get '/bars' => 'bars#index'
    get '/intellectual' => 'intellectual#index'
    get '/shopping' => 'shopping#index'
    get '/bored' => 'bored#index'
    get '/active' => 'active#index'
    get '/outdoors' => 'outdoors#index'
    get '/broke' => 'broke#index'
  end
  post '/attendees' => 'attendees#create'

  get '/signin' => 'authenticates#signin'
  post '/signin' => 'authenticates#create'

  get '/signup' => 'registers#signup'
  post '/signup' => 'registers#create'

  get '/signout' => 'authenticates#destroy'

end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :subcat

  has_many :spots
  has_many :comments
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :pics
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @subscription = Subscription.new
  end
end

app/views/places/index.html.erb
<%= page_header "Places" do%>
<% end %>
<table class = 'table'>
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Description
      </th>
      <th>
        Location
      </th>
      <th>
        Belongs to...
      </th>
    </tr>
  </thead>
  <tbody>
    <% @places.order(:subcat_id, :location).each do |place| %>
      <tr>
        <td>
          <%= link_to place.name, place_path(place) %>
        </td>
        <td>
          <%= place.description %>
        </td>
        <td>
          <%= place.location %>
        </td>
        <td>
          <%= link_to image_tag(place.subcat.cat.image, width: "50em"), "categories/#{place.subcat.cat.name.downcase}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/places/show.html.erb
<%= page_header "#{@place.name}" %>
<div class = 'container'>
<div style='width:53%'>
  <%= @place.description %><hr>
</div>
<div class='map' style='margin-right:10%'></div>
<br><br>
<% first_six = @place.pics.first(6) %>
<% first_six.each do |pic| %>
  <%= link_to image_tag(pic.image.url, width: "20%",
    alt: "Whoops! Your image isn't showing up. Please make sure it's an image file.
          This is a #{pic.image.url.rpartition('.').last.upcase} file."),
    place_pic_path(@place, pic) %>
<% end %>
<div style='float:right;margin-right:10%'>
  <% if @place.pics.length > 6 %>
    <%= link_to "See more images >>", place_pics_path(@place) %>
  <% end %>
</div>
<%= link_to "Add a new image", new_place_pic_path(@place), style: 'display:inline-block' %>

</div>
<hr>
<h2>Subscribers</h2>
<div class='container'>
  <%= form_for @subscription, url: {action: "create", controller: 'subscriptions', params: {place_id: @place.id}} do |f| %>
    <%= f.submit 'Subscribe!', class: 'btn-submit' %>
  <% end %>
  <% @place.subscriptions.all.order(role: :desc).each do |subb| %>
    <%= link_to (image_tag(subb.user.avatar, width: '50em') + subb.user.full_name), user_path(subb.user) %>
    <%= "(#{subb.role})" %><br>
  <% end %>
</div>
<script>

$(document).ready(function(){
  var myLatLng = new google.maps.LatLng(40.0293099,-105.2399774);
  var myOptions = {
    zoom: 14,
    center: myLatLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    //disableDefaultUI: true,
  };
  map = new google.maps.Map(
    document.getElementsByClassName('map')[0], myOptions
  )
});
</script>